theme: jekyll-theme-slate
title: A blog series on recent papers on Visually Rich Documents
description: Ritesh Sarkhel
google_analytics: "UA-165274113-1"
show_downloads: "true"
github:
  zip_url: https://github.com/sarkhelritesh/vrd/blob/main/vrd.bib
