theme: jekyll-theme-minimal
title: List of recent papers on IE from Visually Rich Documents
description: This is an attenmpt to create a resource page for researchers working on Information Extraction from Visually Rich Documents
google_analytics: "UA-165274113-1"
logo: R.ico
