theme: jekyll-theme-minimal
title: List of recent papers on IE from Visually Rich Documents
description: This is a resource page intended to help researchers working on Information Extraction from Visually Rich Documents
google_analytics: "UA-165274113-1"
show_downloads: "true"
logo: "R.jpg"
