theme: jekyll-theme-minima
title: List of recent papers on Visually Rich Documents
description: This is a resource page intended to help researchers working on various tasks related to Visually Rich Documents
google_analytics: "UA-165274113-1"
show_downloads: "true"
