theme: jekyll-theme-slate
title: Awesome resource for Visually Rich Documents
description: A series on recent papers focusing on Visually Rich Documents
google_analytics: "UA-165274113-1"
show_downloads: "false"
