theme: jekyll-theme-minimal
title: Awesome resource on IE from Visually Rich Documents
description: This is an amateurish attempt to create a one-stop resource page for research on Information Extraction from Visually Rich Documents
