theme: jekyll-theme-slate
title: A series on Visually Rich Documents
description: A brief overview of recent papers on Visually Rich Documents
google_analytics: "UA-165274113-1"
show_downloads: "false"
