theme: jekyll-theme-minimal
title: Awesome resource on IE from Visually Rich Documents
description: This is an attempt to create a resource page for contemporary research on Information Extraction from Visually Rich Documents
